# lightning.pytorch==2.0.0
# name: dev-refactor-wnb
name: crypto
version: v34

seed_everything: 42
trainer:
  accelerator: cpu
  precision: 16-mixed
  max_epochs: 200
  plugins:
    - AsyncCheckpointIO

model:
  class_path: LitCrypto
  init_args:
    net:
      class_path: Time2Vec
      init_args:
        input_size: 9
        activation: sin
        hidden_dim: 200
        out_dim: 4
        batch_size: ${data.init_args.batch_size}
        lstm_hidden_dim: 20
        lstm_layer: 1

    loss_module:
      class_path: MeanSquaredError

data:
  class_path: CryptoDataModule
  init_args:
    csv_path: data/bitcoin_2017_to_2023.csv
    batch_size: 32
    val_split: 0.2

optimizer:
  class_path: SGD
  init_args:
    lr: 1e-3
    momentum: 0.9
    weight_decay: 5e-4

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: ${trainer.max_epochs}
# ckpt_path: logs/debug-resume/version_0/fit/checkpoints/last.ckpt

model_ckpt:
  dirpath: "gs://crypto-data-12"
